### ISSUE TITLE
can to mine without walletSeed ?

### ISSUE THREAD

**Issue by ags-21ct** [MatthewDLudwig/NimiqWrapper#2]
let inits = {
        walletSeed: "01 08 80 CB 6F 9C BA 2A 6A D6 7F 3B BF 1E 2F 7D C0 6F D3 66 9F 1D 19 70 9C 6D 7B 1B 1D 2D FD F4 E5 32 0A 7C F9 24 97 48 76 FF 2D 9F 5B A6 9C D8 5C 46 A9 76 3A 94",
        walletKey: "Password",
        mineToAddr: "NQ59 YQMY GMSR 31V5 KCX9 UAX7 XX54 875N KAAC"
    };

mineToAddr will be get rewards ?

**Comment by MatthewDLudwig** [comment]
You are correct!  NimiqWrapper will be undergoing a rewrite within the next 2 weeks to help make starting a node and mining even easier, but for now this will work.  If you're only mining you can leave out walletSeed and walletKey as you aren't sending any transactions or need a wallet.  Remember to keep an eye out for that update!
